// Loads .env into process.env. Must run before anything reads process.env.
require('dotenv').config();

const express = require('express');
const swaggerUi = require('swagger-ui-express');

const { initDb } = require('./data/database');
const routes = require('./routes');
// Generated by `npm run swagger`. It is committed to the repo so the deployed
// server can serve the docs without running the generator — and because this is
// a plain `require`, a missing file stops the server immediately rather than
// deploying an API whose documentation silently 404s.
const swaggerDocument = require('./swagger-output.json');

const app = express();
const port = process.env.PORT || 8080;

// Parse incoming JSON request bodies into req.body.
app.use(express.json());

// The assignment requires the API be callable "from external sources", so allow
// any origin. Note this is a *browser* restriction only — curl and the VS Code
// REST Client ignore CORS entirely, which is why those work without it.
//
// Week 04 note: `Allow-Origin: *` and cookies are mutually exclusive by spec, so
// a cross-origin page could not send the session cookie. That is fine here —
// Swagger UI is served from this same origin, so its requests are not
// cross-origin and the cookie rides along normally.
app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'Origin, X-Requested-With, Content-Type, Accept, Z-Key',
  );
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  next();
});

// Interactive API documentation. swaggerUi.serve hosts the UI's own CSS and JS;
// swaggerUi.setup builds the page from the generated OpenAPI document.
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

app.use('/', routes);

// Nothing above matched, so the path does not exist. Without this, Express
// answers with its own HTML error page — unhelpful for an API whose callers
// expect JSON.
app.use((req, res) => {
  res.status(404).json({ message: `Not found: ${req.method} ${req.originalUrl}` });
});

// The error handler. Express recognises it as one purely because it takes FOUR
// parameters, so `next` must stay in the signature even though it is unused —
// hence the underscore, which the ESLint config is set up to ignore.
//
// Express 5 (unlike Express 4) automatically forwards a rejected promise from
// an async route handler here, so this also catches anything a controller's
// try/catch misses.
app.use((err, req, res, _next) => {
  console.error('Unhandled error:', err);

  // Deliberately generic. An error message can leak connection strings or file
  // paths, so the details go to the server log and the caller gets none of it.
  res.status(500).json({ message: 'An unexpected server error occurred.' });
});

// Connect to MongoDB first; only start accepting requests once it succeeded,
// so no request can ever hit an uninitialized database.
initDb()
  .then(() => {
    app.listen(port, () => {
      console.log(`Database connected. Web server running at http://localhost:${port}`);
      console.log(`API documentation at http://localhost:${port}/api-docs`);
    });
  })
  .catch((err) => {
    console.error('Failed to connect to MongoDB:', err.message);
    process.exit(1);
  });
